#!/bin/sh
set -e
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE lab_app LOGIN PASSWORD '${LAB_APP_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO lab_app;
  GRANT USAGE ON SCHEMA public TO lab_app;
EOSQL